### ISSUE TITLE
DAP Intro Issues

### ISSUE THREAD

**Issue by micahlee** [conjurdemos/dap-intro#76]
This issue is for two defects that cause issues attempting non-trivial cluster operations with DAP intro:

- `jq` is missing from the API client container image. However, it is used in the API scripts.
- The CLI container references a specific DAP node, rather than the Master LB. This prevents the client from working after a standby promotion.

Connected to Connected to https://github.com/conjurinc/appliance/issues/1122

**Comment by sgnn7** [comment]
Closed via #77
